feat:refactor to allow cookie retrieval, renewal and verification for multiple realms
dot-base/authentication-gateway pull request #10
Opened 2021-12-21 20:25 UTC by andreakreichgauer

This introduces retrieval, renewal and verification for multiple realms - currently dotbase and patients.

BREAKING CHANGE: routes for login and renewal changed to `auth/login/<realmName>` and `auth/renew/<realmName>`

2021-12-22 10:45 UTC, friedow requested changes

2021-12-22 10:45 UTC, friedow commented on src/utils/realms.ts
> +import JwtUtil from "./Jwt";
Should be an @/ import.
```suggestion
import JwtUtil from "@/utils/Jwt";
```

2021-12-22 10:45 UTC, friedow commented on src/models/realms/DotbaseRealm.ts
> +  }
These can be static.

2021-12-22 10:45 UTC, friedow commented on src/models/realms/DotbaseRealm.ts
> +}
Instead of implementing a singleton pattern, you can use the node js default export to create a single instance which also creates a singleton.

```suggestion
DotbaseRealmModel implements RealmConfig {
  constructor() {
    this._certificateModel = new CertificateModel();
    this._certificateModel.fetchCertificates(this.realmName);
  }

  private _certificateModel;

  public get realmName(): string {
    if (!process.env.KEYCLOAK_DOTBASE_REALM_NAME)
      throw new Error("Keycloak realm name is not defined.");
    return process.env.KEYCLOAK_DOTBASE_REALM_NAME;
  }

  public get clientId(): string {
    if (!process.env.KEYCLOAK_DOTBASE_REALM_CLIENT_ID)
      throw new Error("Keycloak client ID is not defined.");
    return process.env.KEYCLOAK_DOTBASE_REALM_CLIENT_ID;
  }

  public get clientSecret(): string {
    if (!process.env.KEYCLOAK_DOTBASE_REALM_CLIENT_SECRET)
      throw new Error("Keycloak client secret is not defined.");
    return process.env.KEYCLOAK_DOTBASE_REALM_CLIENT_SECRET;
  }

  public certs(): string[] {
    return this._certificateModel.certificates(this.realmName);
  }
}

export default new DotbaseRealmModel();
```

2021-12-22 10:45 UTC, friedow commented on src/models/Certificate.ts
>    }
fetchCertificate should be private and the constructor should take the realmName argument instead.

2021-12-22 10:45 UTC, friedow commented on src/models/realms/PatientRealm.ts
> +import CertificateModel from "@/models/Certificate";
same changes as in DotbaseRealm

2021-12-22 10:45 UTC, friedow commented on src/utils/realms.ts
> +    if (!realmName) throw new Error("Access token is invalid.");
Whether the access token is valid or not should be decided by business logic (validate func) instead of utils.

```suggestion
    if (!realmName) throw new Error("Access token does not contain a realmName.");
```

2021-12-22 10:45 UTC, friedow commented on src/services/Crypto.ts
> +    ];
The service should not depend that highly onto explicit realms. Lets talk about decoupling that.

2021-12-22 10:45 UTC, friedow commented on src/routers/Renewal.ts
> +      req.params.realmName,
I think to refactor code in deeper layers it would be nice to pass the realm config instead of the realm name. That also validates the realm name right here.

2021-12-22 13:27 UTC, andreakreichgauer commented on src/models/realms/DotbaseRealm.ts
> +}
yes, I thought about doing so, too. But this would not work here, since `this.realmName` is still undefined when the constructor is called

2022-01-03 09:04 UTC, friedow approved these changes

2022-01-03 09:06 UTC, merged